# Generated by Django 3.1 on 2020-09-22 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIN', models.CharField(max_length=11, verbose_name='National Identification Number')),
                ('BVN', models.CharField(max_length=11)),
                ('upload_id', models.ImageField(upload_to='ids/', verbose_name='upload id')),
                ('bank_name', models.CharField(max_length=50, verbose_name='bank name')),
                ('bank_account_number', models.CharField(max_length=10, verbose_name='bank account number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user Verification',
                'verbose_name_plural': 'user Verifications',
            },
        ),
    ]
