# Generated by Django 3.1 on 2020-09-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200927_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverification',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userverification', verbose_name='verification'),
        ),
    ]
