# Generated by Django 3.1 on 2020-09-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200927_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification',
        ),
        migrations.AddField(
            model_name='userverification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
