# Generated by Django 3.1 on 2020-09-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200928_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='BVN',
            field=models.CharField(max_length=20, verbose_name='Bank Verification Number'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='NIN',
            field=models.CharField(max_length=20, verbose_name='National Identification Number'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='account_number',
            field=models.CharField(max_length=20, verbose_name='bank account number'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='id_type',
            field=models.CharField(max_length=500, verbose_name='type of ID'),
        ),
    ]
