# Generated by Django 3.1 on 2020-09-09 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_uploaded', models.BooleanField(verbose_name='is uploaded')),
                ('in_transit', models.BooleanField(verbose_name='in transit')),
                ('is_delivered', models.BooleanField(verbose_name='is delivered')),
            ],
            options={
                'verbose_name': 'Tracker',
                'verbose_name_plural': 'Trackers',
            },
        ),
        migrations.CreateModel(
            name='PackageVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIN', models.CharField(max_length=11, verbose_name='National Identification Number')),
                ('BVN', models.CharField(max_length=11)),
                ('upload_id', models.ImageField(height_field='height', upload_to='ids/', verbose_name='upload id', width_field='width')),
                ('bank_name', models.CharField(max_length=50, verbose_name='bank name')),
                ('bank_account_number', models.CharField(max_length=10, verbose_name='bank account number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Package Verification',
                'verbose_name_plural': 'Package Verifications',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('weight', models.PositiveIntegerField(verbose_name='weight')),
                ('category', models.CharField(choices=[('CLOTHS', 'Cloths'), ('DOCUMENTS', 'Documents'), ('GROCERY', 'Grocery'), ('OTHER', 'Other')], max_length=50, verbose_name='category')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('pick_location', models.CharField(max_length=50, verbose_name='pick up location')),
                ('dest_location', models.CharField(max_length=50, verbose_name='delivery location')),
                ('delivered_on', models.DateTimeField(verbose_name='delivery time')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('security_code', models.CharField(max_length=20, verbose_name='security code')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='carrier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tracker', verbose_name='tracker')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
