# Generated by Django 3.1 on 2020-09-18 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='carrier'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='in_transit',
            field=models.BooleanField(default=False, verbose_name='in transit'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='is delivered'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='is_uploaded',
            field=models.BooleanField(default=False, verbose_name='is uploaded'),
        ),
    ]
