# Generated by Django 3.1 on 2020-09-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200918_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='name',
            field=models.CharField(default='jerry', max_length=200),
            preserve_default=False,
        ),
    ]
