# Generated by Django 3.1 on 2020-09-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tracker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='name',
        ),
    ]
