# Generated by Django 3.1 on 2020-09-21 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_tracker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='tracker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tracker', verbose_name='tracker'),
        ),
        migrations.AlterField(
            model_name='packageverification',
            name='upload_id',
            field=models.ImageField(upload_to='ids/', verbose_name='upload id'),
        ),
    ]
