# Generated by Django 3.1 on 2020-09-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200921_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='tracker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tracker', verbose_name='tracker'),
        ),
        migrations.DeleteModel(
            name='PackageVerification',
        ),
    ]
