# Generated by Django 3.1 on 2020-09-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200922_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivery_period',
            field=models.PositiveIntegerField(default=1, verbose_name='delivery period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='destination',
            field=models.CharField(default='lagos', max_length=50, verbose_name='package destination city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='origin',
            field=models.CharField(default='abuja', max_length=50, verbose_name='package origin city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='HIGH', max_length=50, verbose_name='Package Priority'),
            preserve_default=False,
        ),
    ]
