# Generated by Django 3.1 on 2020-09-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200922_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivery time'),
        ),
    ]
