# Generated by Django 3.1 on 2020-09-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200923_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='security_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='security code'),
        ),
    ]
