# Generated by Django 3.1 on 2020-09-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200923_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='is_uploaded',
            new_name='is_confirmed',
        ),
    ]
