# Generated by Django 3.1 on 2020-10-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201005_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recievers_first_name',
            field=models.CharField(default='jerry', max_length=20, verbose_name='recievers first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='recievers_last_name',
            field=models.CharField(default='john', max_length=20, verbose_name='recievers last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='recievers_phone_number',
            field=models.CharField(default='09087654', max_length=20, verbose_name='recievers phone number'),
            preserve_default=False,
        ),
    ]
